// Parasite Extension System for skill-router
// Enables runtime injection without modifying source code
// Each client gets an extension folder that skill-router manages

import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, rmSync } from "node:fs";
import { join } from "node:path";
import { CLIENTS } from "../clients.js";
import { VERSION } from "../engine.js";

/**
 * Parasite Mode: Inject enhancements at runtime without modifying source
 * - Creates extension folders for each client
 * - Wraps upstream servers with enhancement layers
 * - Provides build-time hooks (Vite/webpack plugins)
 * - Never touches original source files
 */

const EXTENSION_DIR = ".skill-router-extensions";
const INJECTION_MANIFEST = "parasite-manifest.json";

// Get extension directory for a client
export function getExtensionDir(client) {
  const base = client.user || join(process.env.HOME || process.env.USERPROFILE, ".agents", "skills");
  return join(base, EXTENSION_DIR);
}

// Initialize extension directory for a client
export function initExtensions(client) {
  const extDir = getExtensionDir(client);
  mkdirSync(extDir, { recursive: true });
  
  const manifest = {
    version: VERSION,
    created: new Date().toISOString(),
    injections: [],
    hooks: [],
    wrapped: false
  };
  
  const manifestPath = join(extDir, INJECTION_MANIFEST);
  if (!existsSync(manifestPath)) {
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  }
  
  return extDir;
}

// Load injection manifest
export function loadManifest(extDir) {
  const manifestPath = join(extDir, INJECTION_MANIFEST);
  if (!existsSync(manifestPath)) {
    return { version: VERSION, created: new Date().toISOString(), injections: [], hooks: [], wrapped: false };
  }
  return JSON.parse(readFileSync(manifestPath, "utf-8"));
}

// Save injection manifest
export function saveManifest(extDir, manifest) {
  const manifestPath = join(extDir, INJECTION_MANIFEST);
  writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
}

/**
 * Runtime Injection: Add a runtime enhancement
 * @param {Object} client - Client object
 * @param {Object} injection - { id, type, code, target, position }
 *   type: 'pre-init' | 'post-init' | 'middleware' | 'hook'
 *   target: function or module path to intercept
 *   position: 'before' | 'after' | 'wrap'
 */
export function addInjection(client, injection) {
  const extDir = initExtensions(client);
  const manifest = loadManifest(extDir);
  
  const entry = {
    id: injection.id || `injection-${Date.now()}`,
    type: injection.type || "hook",
    code: injection.code,
    target: injection.target,
    position: injection.position || "wrap",
    created: new Date().toISOString(),
    enabled: true
  };
  
  manifest.injections.push(entry);
  saveManifest(extDir, manifest);
  
  // Write the injection code file
  const codeFile = join(extDir, `${entry.id}.js`);
  writeFileSync(codeFile, entry.code);
  
  return entry;
}

/**
 * Build-time Hook: Generate Vite/webpack plugin code
 * @param {Object} options - { format: 'vite' | 'webpack', injections: [] }
 */
export function generateBuildHook(options = {}) {
  const { format = "vite", injections = [], env = {} } = options;
  const envBlock =
    Object.keys(env).length > 0
      ? "\n  // Project env isolation (skill-router.json \"env\")\n  " +
        Object.entries(env)
          .map(([k, v]) => `process.env.${k} = ${JSON.stringify(v)};`)
          .join("\n  ") +
        "\n"
      : "";
  
  if (format === "vite") {
    return `
// Auto-generated by skill-router parasite system
// Vite plugin for runtime injection
export function skillRouterParasite(options = {}) {
  ${envBlock}  const injections = ${JSON.stringify(injections)};
  
  return {
    name: 'skill-router-parasite',
    transformIndexHtml(html) {
      // Inject pre-init code into <head>
      const preInit = injections
        .filter(i => i.type === 'pre-init' && i.enabled)
        .map(i => \`<script>\${i.code}</script>\`)
        .join('\\n');
      
      if (preInit) {
        return html.replace('<head>', \`<head>\\n\${preInit}\`);
      }
      return html;
    },
    configResolved(config) {
      // Wrap dev server middleware
      config.server.middlewares.use((req, res, next) => {
        // Inject middleware code here
        next();
      });
    }
  };
}`;
  }
  
  // Webpack format
  return `
// Auto-generated by skill-router parasite system
// Webpack plugin for runtime injection
class SkillRouterParasite {
  constructor(options = {}) {
    ${envBlock}    this.injections = ${JSON.stringify(injections)};
  }
  
  apply(compiler) {
    compiler.hooks.compilation.tap('SkillRouterParasite', (compilation) => {
      compilation.hooks.processAssets.tap('SkillRouterParasite', () => {
        // Inject into HTML template
        const html = compilation.getAsset('index.html');
        if (html) {
          const preInit = this.injections
            .filter(i => i.type === 'pre-init' && i.enabled)
            .map(i => \`<script>\${i.code}</script>\`)
            .join('\\n');
          
          const newSource = html.source.source().replace('<head>', \`<head>\\n\${preInit}\`);
          compilation.updateAsset('index.html', new compiler.webpack.sources.RawSource(newSource));
        }
      });
    });
  }
}

module.exports = SkillRouterParasite;`;
}

/**
 * Server Wrapper: Wrap an upstream server with enhancement layers
 * @param {Object} options - { serverPath, enhancements: [] }
 */
export function generateServerWrapper(options = {}) {
  const { serverPath, enhancements = [], env = {} } = options;
  const envBlock =
    Object.keys(env).length > 0
      ? "\n// Project env isolation (skill-router.json \"env\")\n" +
        Object.entries(env)
          .map(([k, v]) => `process.env.${k} = ${JSON.stringify(v)};`)
          .join("\n") +
        "\n"
      : "";

  // Inline case bodies at generation time so no template interpolation is
  // left for runtime evaluation inside the generated wrapper.
  const enhancementCases = enhancements
    .filter((e) => e.enabled)
    .map((e) => {
      const code = e.code || "";
      const target = e.target || "default";
      switch (e.type) {
        case "middleware":
          return `    case '${target}':\n      app.use((req, res, next) => {\n        ${code}\n        next();\n      });\n      break;`;
        case "route":
          return `    case '${target}':\n      ${code}\n      break;`;
        default:
          return `    case '${target}':\n      ${code}\n      break;`;
      }
    })
    .join("\n");

  return `
// Auto-generated by skill-router parasite system
// Server wrapper that enhances upstream without modification
import { createServer as createUpstreamServer } from '${serverPath || './upstream-server.js'}';

const enhancements = ${JSON.stringify(enhancements)};
${envBlock}
// Apply enhancements in order.
function applyEnhancements(app) {
  for (const enhancement of enhancements) {
    if (!enhancement.enabled) continue;
    switch (enhancement.type) {
      ${enhancementCases}
    }
  }
  return app;
}

export function createServer(options = {}) {
  const app = createUpstreamServer(options);
  return applyEnhancements(app);
}

// Re-export everything from upstream
export * from '${serverPath || './upstream-server.js'}';`;
}

/**
 * Traceability Protection: Obfuscate extracted code
 * @param {string} code - Code to protect
 * @param {Object} options - { level: 'light' | 'medium' | 'heavy' }
 */
export function protectTraceability(code, options = {}) {
  const { level = "medium" } = options;
  
  // Light: Remove comments, minify variable names
  if (level === "light") {
    return code
      .replace(/\/\/.*$/gm, "") // Remove line comments
      .replace(/\/\*[\s\S]*?\*\//g, "") // Remove block comments
      .replace(/\s+/g, " ") // Minify whitespace
      .trim();
  }
  
  // Medium: Rename variables, add dead code
  if (level === "medium") {
    const vars = ["_0x1a2b", "_0x3c4d", "_0x5e6f", "_0x7a8b", "_0x9c0d"];
    let protectedCode = code;
    
    // Replace common variable patterns
    const varNames = ["temp", "result", "data", "item", "value", "index", "count", "len"];
    varNames.forEach((name, i) => {
      protectedCode = protectedCode.replace(new RegExp(`\\b${name}\\b`, "g"), vars[i % vars.length]);
    });
    
    // Add dead code
    const deadCode = `
// Dead code for obfuscation
const _unused_${Date.now()} = Math.random() > 0.5 ? null : undefined;
if (_unused_${Date.now()}) { /* unreachable */ }
`;
    
    return deadCode + protectedCode;
  }
  
  // Heavy: Full obfuscation with control flow flattening
  if (level === "heavy") {
    // Split code into chunks and reorder
    const lines = code.split("\n");
    const chunks = [];
    for (let i = 0; i < lines.length; i += 3) {
      chunks.push(lines.slice(i, i + 3).join("\n"));
    }
    
    // Shuffle chunks (deterministic based on content hash)
    const shuffled = chunks.sort(() => 0.3 - Math.random());
    
    // Add decoder function
    const decoder = `
// Decoder function
function _decode_${Date.now()}(chunks) {
  return chunks.join('\\n');
}
`;
    
    return decoder + `const _chunks = ${JSON.stringify(shuffled)};\n_decode_${Date.now()}(_chunks);`;
  }
  
  return code;
}

/**
 * List all extensions for a client
 */
export function listExtensions(client) {
  const extDir = getExtensionDir(client);
  if (!existsSync(extDir)) {
    return { injections: [], hooks: [], wrapped: false };
  }
  
  const manifest = loadManifest(extDir);
  return {
    injections: manifest.injections || [],
    hooks: manifest.hooks || [],
    wrapped: manifest.wrapped || false,
    path: extDir
  };
}

/**
 * Enable/disable an injection
 */
export function toggleInjection(client, injectionId, enabled) {
  const extDir = getExtensionDir(client);
  const manifest = loadManifest(extDir);
  
  const injection = manifest.injections.find(i => i.id === injectionId);
  if (injection) {
    injection.enabled = enabled;
    saveManifest(extDir, manifest);
    return true;
  }
  return false;
}

/**
 * Remove an injection
 */
export function removeInjection(client, injectionId) {
  const extDir = getExtensionDir(client);
  const manifest = loadManifest(extDir);
  
  manifest.injections = manifest.injections.filter(i => i.id !== injectionId);
  saveManifest(extDir, manifest);
  
  // Remove the code file
  const codeFile = join(extDir, `${injectionId}.js`);
  if (existsSync(codeFile)) {
    rmSync(codeFile);
  }
  
  return true;
}

/**
 * Get injection status for all clients
 */
export function getInjectionStatus() {
  const status = [];
  
  for (const client of CLIENTS) {
    const ext = listExtensions(client);
    status.push({
      client: client.id,
      label: client.label,
      injections: ext.injections.length,
      active: ext.injections.filter(i => i.enabled).length,
      path: ext.path
    });
  }
  
  return status;
}
